version: '3'
services:
  web:
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
  frontend:
    image: nginx:alpine
    volumes:
      - ./app/index.html:/usr/share/nginx/html/index.html
    ports:
      - "8080:80"
